name: Build and Sign APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Install dependencies
      run: npm ci

    - name: Build Vue.js App
      run: npm run build

    - name: Sync Capacitor
      run: npx cap sync android

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Fix gradlew permissions
      run: chmod +x android/gradlew

#    - name: Update Gradle to 8.9
#      run: |
#        cd android
#        ./gradlew wrapper --gradle-version 8.9

    - name: Decode Keystore
      run: |
        echo "${{ secrets.KEYSTORE }}" | base64 --decode > android/app/app/release.jks

    - name: Build Signed APK
      run: |
        cd android
        ./gradlew assembleRelease \
          -Pandroid.injected.signing.store.file=app/release.jks \
          -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASS }} \
          -Pandroid.injected.signing.key.alias=${{ secrets.KEYSTOREALIAS }} \
          -Pandroid.injected.signing.key.password=${{ secrets.KEYSTOREALIAS_PASS }}

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: android/app/build/outputs/apk/release/app-release.apk
