name: Android Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get package version
      id: package-version
      run: |
        VERSION=$(jq -r .version package.json)
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "TAG=v${VERSION}" >> $GITHUB_ENV

    - name: Set up Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'

    - name: Install dependencies
      run: npm ci

    - name: Build Vue.js App
      run: npm run build

    - name: Sync Capacitor
      run: npx cap sync android

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Fix gradlew permissions
      run: chmod +x android/gradlew

    - name: Decode Keystore
      run: |
        mkdir -p android/app
        echo "${{ secrets.KEYSTORE }}" | base64 --decode > android/app/release.jks

    - name: Set Environment Variables
      run: |
        echo "KEYSTORE_PASS=${{ secrets.KEYSTORE_PASS }}" >> $GITHUB_ENV
        echo "KEYSTOREALIAS=${{ secrets.KEYSTOREALIAS }}" >> $GITHUB_ENV
        echo "KEYSTOREALIAS_PASS=${{ secrets.KEYSTOREALIAS_PASS }}" >> $GITHUB_ENV

    - name: Build Signed APK
      run: |
        cd android
        ./gradlew assembleRelease --no-daemon \
          -PKEYSTORE_PASS=${{ secrets.KEYSTORE_PASS }} \
          -PKEYSTOREALIAS=${{ secrets.KEYSTOREALIAS }} \
          -PKEYSTOREALIAS_PASS=${{ secrets.KEYSTOREALIAS_PASS }}

    - name: Rename APK
      run: |
        mv android/app/build/outputs/apk/release/app-release.apk \
          "TouchNStars-${{ steps.package-version.outputs.version }}.apk"

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.TAG }}
        name: Android ${{ steps.package-version.outputs.version }}
        generate_release_notes: true
        files: |
          TouchNStars-${{ steps.package-version.outputs.version }}.apk
